import { type Product } from "./ProductCard";

export const products: Product[] = [
    {
        name:"TLS Knit Cap",
        category:"knit-cap",
        shortDescription:"Some description goes here",
        price:32,
        oldPrice:56,
        image:"/images/store/bonnet.webp",
        link:"/examples/ecommerce/product",
    },
    {
        name:"TLS Dress",
        category:"knit-cap",
        shortDescription:"Some description goes here",
        price:69,
        oldPrice:119,
        image:"/images/store/dress.webp",
        link:"/examples/ecommerce/product",
    },
    {
        name:"Clein Sports Bottle",
        category:"flask",
        shortDescription:"Some description goes here",
        price:22,
        image:"/images/store/gourde1.webp",
        link:"/examples/ecommerce/product",
    },
    {
        name:"Nike Sports Bottle",
        category:"flask",
        shortDescription:"Some description goes here",
        price:29,
        image:"/images/store/gourde2.webp",
        link:"/examples/ecommerce/product",
    },
    {
        name:"LA T-Shirt",
        category:"t-shirt",
        shortDescription:"Some description goes here",
        price:19,
        image:"/images/store/t-shirt1.webp",
        link:"/examples/ecommerce/product",
    },
    {
        name:"Nike custom T-Shirt",
        category:"t-shirt",
        shortDescription:"Some description goes here",
        price:26,
        oldPrice:39,
        image:"/images/store/t-shirt2.webp",
        link:"/examples/ecommerce/product",
    },
    {
        name:"CAL Long Sleeve",
        category:"longslive t-shirt",
        shortDescription:"Tailus UI California mood t-shirt",
        price:26,
        oldPrice:39,
        image:"/images/store/t-shirt-l1.webp",
        link:"/examples/ecommerce/product",
    },
    {
        name:"705 Long Sleeve",
        category:"longslive t-shirt",
        shortDescription:"Tailus UI Lubumbashi mood t-shirt",
        price:26,
        oldPrice:39,
        image:"/images/store/t-shirt-l2.webp",
        link:"/examples/ecommerce/product",
    },
    {
        name:"CAL Long Sleeve",
        category:"longslive t-shirt",
        shortDescription:"Tailus UI California mood t-shirt",
        price:26,
        oldPrice:39,
        image:"/images/store/t-shirt-l3.webp",
        link:"/examples/ecommerce/product",
    },
]